# Generated by Django 5.2.11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("support_tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_tickets_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="attachment",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to="support_tickets/%Y/%m/"),
        ),
    ]
