# Generated by Django 5.2.11 on 2026-02-11 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('probability', models.CharField(blank=True, max_length=50, null=True)),
                ('mitigation', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='open', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='processes.process')),
            ],
            options={
                'db_table': 'risks',
            },
        ),
        migrations.CreateModel(
            name='RiskMatrixHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.IntegerField()),
                ('probability', models.IntegerField()),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_history', to='risks.risk')),
            ],
            options={
                'db_table': 'risk_matrix_history',
            },
        ),
    ]
