# Generated by Django 5.2.11 on 2026-02-11 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('direccionamiento_estrategico', 'Direccionamiento estrategico'), ('proceso_misional', 'Proceso misional'), ('proceso_apoyo', 'Proceso apoyo'), ('proceso_evaluacion', 'Proceso evaluacion')], default='proceso_misional', max_length=80)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_revision', 'En revision')], default='activo', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_processes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessCharacterization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('inputs', models.TextField(blank=True, null=True)),
                ('outputs', models.TextField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=200, null=True)),
                ('resources', models.TextField(blank=True, null=True)),
                ('related_documents', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characterization', to='processes.process')),
            ],
            options={
                'db_table': 'process_characterization',
            },
        ),
    ]
